App/views/user.py
from flask import (
    Blueprint,
    render_template,
    url_for,
    request,
    redirect,
    flash,
)
from App.models import (
    User,
    Recipe,
    Ingredient,
    Saved,
)
from App import db, bcrypt
from App.forms import (
    UpdateProfileForm,
    RecipeForm,
    ChangePasswordForm,
)
from Controls import PassiveControls
user = Blueprint("user", __name__, static_folder="static", template_folder="templates")


@user.route('/')
def index():
    valid = PassiveControls.validation()
    if valid[0] and valid[2] == "user":
        editor_recipe = Recipe.query.filter_by(status=1).all()
        featured = Recipe.query.filter_by(status=2)
        users = User.query.filter_by(type="user").paginate(per_page=3)
        return render_template('user/index.html', editor_recipe=editor_recipe, featured=featured, users=users)
    else:
        return render_template("error.html", error=PassiveControls.ErrMsg.access)


@user.route('/profile')
def profile():
    valid = PassiveControls.validation()
    if valid[0] and valid[2] == "user":
        user_data = User.query.get_or_404(valid[1])
        recipe = Recipe.query.filter_by(created_by=valid[1]).all()
        return render_template('user/profile.html', user=valid[3], profile=user_data, recipes=recipe)
    else:
        return render_template("error.html", error=PassiveControls.ErrMsg.access)


@user.route('/edit/profile', methods=["POST", "GET"])
def edit_profile():
    valid = PassiveControls.validation()
    if valid[0] and valid[2] == "user":
        user = User.query.get_or_404(valid[1])
        form = UpdateProfileForm()
        if request.method == "POST":
            if form.image.data:
                image_file = PassiveControls.save_file(form.image.data)
                user.profile_pic = image_file
            user.name = form.name.data
            user.username = form.username.data
            user.email = form.email.data
            db.session.commit()
            return redirect(url_for('user.profile'))
        elif request.method == "GET":
            form.name.data = user.name
            form.username.data = user.username
            form.email.data = user.email
            form.designation.data = user.designation
            return render_template('user/edit_profile.html', user=valid[3], form=form)
    else:
        return render_template("error.html", error=PassiveControls.ErrMsg.access)


@user.route('/password/change', methods=["POST", "GET"])
def change_password():
    valid = PassiveControls.validation()
    if valid[0] and valid[2] == "user":
        form = ChangePasswordForm()
        users = User.query.get_or_404(valid[1])
        if form.validate_on_submit():
            hashed_pass = bcrypt.generate_password_hash(form.new_password.data).decode('utf-8')
            users.password = hashed_pass
            db.session.commit()
            return redirect(url_for('user.index'))
        return render_template('user/change_password.html', user=valid[3], users=users, form=form)
    else:
        return render_template("error.html", error=PassiveControls.ErrMsg.access)


@user.route('/chefs')
def cooks():
    valid = PassiveControls.validation()
    if valid[0] and valid[2] == "user":
        page = request.args.get('page', 1, type=int)
        users = User.query.filter_by(type="user").paginate(page=page, per_page=5)
        return render_template('user/cooks.html', user=valid[3], users=users)
    else:
        return render_template("error.html", error=PassiveControls.ErrMsg.access)


@user.route('/chef/<int:user_id>')
def user_profile(user_id):
    valid = PassiveControls.validation()
    if valid[0] and valid[2] == "user":
        user_data = User.query.get_or_404(user_id)
        recipe = Recipe.query.filter_by(created_by=valid[1]).all()
        return render_template('user/user_profile.html', user=valid[3], profile=user_data, recipes=recipe)
    else:
        return render_template("error.html", error=PassiveControls.ErrMsg.access)


@user.route('/ingredients')
def ingredients():
    valid = PassiveControls.validation()
    if valid[0] and valid[2] == "user":
        page = request.args.get('page', 1, type=int)
        ingredient = Ingredient.query.paginate(page=page, per_page=6)
        return render_template('user/ingredients.html', user=valid[3], ingredients=ingredient)
    else:
        return render_template("error.html", error=PassiveControls.ErrMsg.access)


@user.route('/publish', methods=["POST", "GET"])
def publish_recipe():
    valid = PassiveControls.validation()
    if valid[0] and valid[2] == "user":
        form = RecipeForm()
        if form.validate_on_submit():
            if form.image.data:
                image_file = PassiveControls.save_file(form.image.data)
            recipe = Recipe(title=form.title.data, description=form.description.data,time=form.time.data,
                            servings=form.servings.data, ingredients=form.ingredients.data, image=image_file,
                            approval="-1", status="0", created_by=valid[1])
            db.session.add(recipe)
            db.session.commit()
            flash("Recipe has been published, please wait till its approved by our team.", "success")
            return redirect(url_for('user.index'))
        return render_template('user/publish.html', user=valid[3], form=form)
    else:
        return render_template("error.html", error=PassiveControls.ErrMsg.access)


@user.route('/recipes')
def recipes():
    valid = PassiveControls.validation()
    if valid[0] and valid[2] == "user":
        page = request.args.get('page', 1, type=int)
        recipe = Recipe.query.filter_by(approval=-1 and 1).paginate(page=page, per_page=5)
        return render_template('user/recipes.html', user=valid[3], recipes=recipe)
    else:
        return render_template("error.html", error=PassiveControls.ErrMsg.access)


@user.route('/recipes/own')
def my_recipes():
    valid = PassiveControls.validation()
    if valid[0] and valid[2] == "user":
        recipe = Recipe.query.filter_by(created_by=valid[1]).all()
        return render_template('user/my_recipes.html', user=valid[3], recipes=recipe)
    else:
        return render_template("error.html", error=PassiveControls.ErrMsg.access)


@user.route('/recipe/<int:recipe_id>')
def single_recipe(recipe_id):
    valid = PassiveControls.validation()
    if valid[0] and valid[2] == "user":
        recipe = Recipe.query.get_or_404(recipe_id)
        featured = Recipe.query.filter_by(status=1 and 2)
        ingredient = recipe.ingredients.split(',')
        return render_template('user/single.html', user=valid[3], recipe=recipe, featured=featured, ingredients=ingredient)
    else:
        return render_template("error.html", error=PassiveControls.ErrMsg.access)


@user.route('/recipe/edit/<int:recipe_id>', methods=["POST", "GET"])
def edit_recipe(recipe_id):
    valid = PassiveControls.validation()
    recipe = Recipe.query.get_or_404(recipe_id)
    if valid[0] and valid[2] == "user" and valid[1] == recipe.created_by:
        form = RecipeForm()
        if form.validate_on_submit():
            if form.image.data:
                image_file = PassiveControls.save_file(form.image.data)
                recipe.image = image_file
            recipe.title = form.title.data
            recipe.description = form.description.data
            recipe.time = form.time.data
            recipe.servings = form.servings.data
            recipe.ingredients = form.ingredients.data
            db.session.commit()
            flash('Recipe has been edited!', 'success')
            return redirect(url_for('user.my_recipes'))
        elif request.method == "GET":
            form.title.data = recipe.title
            form.description.data = recipe.description
            form.time.data = recipe.time
            form.servings.data = recipe.servings
            form.ingredients.data = recipe.ingredients
            return render_template('user/edit_recipe.html', user=valid[3], form=form)
    else:
        return render_template("error.html", error=PassiveControls.ErrMsg.access)


@user.route('/recipe/delete/<int:recipe_id>')
def delete_recipe(recipe_id):
    valid = PassiveControls.validation()
    if valid[0] and valid[2] == "user":
        recipe = Recipe.query.get_or_404(recipe_id)
        if recipe.created_by == valid[1]:
            db.session.delete(recipe)
            db.session.commit()
            flash("Recipe has been deleted!", "info")
        else:
            flash("You don't have access to delete this recipe!", "info")
        return redirect(url_for('user.my_recipes'))
    else:
        return render_template("error.html", error=PassiveControls.ErrMsg.access)


@user.route('/save/<int:recipe_id>')
def save_recipe(recipe_id):
    valid = PassiveControls.validation()
    if valid[0] and valid[2] == "user":
        save = Saved( user_id=valid[1], recipe_id=recipe_id)
        db.session.add(save)
        db.session.commit()
        flash("Recipe has been saved!", "info")
        return redirect(url_for('user.saved'))
    else:
        return render_template("error.html", error=PassiveControls.ErrMsg.access)


@user.route('/saved')
def saved():
    valid = PassiveControls.validation()
    if valid[0] and valid[2] == "user":
        saved_recipe = Saved.query.filter_by(user_id=valid[1]).all()
        return render_template('user/saved.html', user=valid[3], saves=saved_recipe)
    else:
        return render_template("error.html", error=PassiveControls.ErrMsg.access)


@user.route('/save/remove/<int:save_id>')
def remove_saved(save_id):
    valid = PassiveControls.validation()
    if valid[0] and valid[2] == "user":
        save = Saved.query.get_or_404(save_id)
        if save.user_id == valid[1]:
            db.session.delete(save)
            db.session.commit()
            flash("Saved Recipe has been removed!", "info")
        else:
            flash("You don't have access to remove this recipe!", "info")

App/templates/user/cooks.html
{% extends "user/base.html" %}

{% block content %}

    <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="row">
              <div class="col-12">
                <div class="section-title">
                  <h2>Recipe Contributors (Chefs)</h2>
                </div>
              </div>
            </div>
            <div class="row">

              <div class="col-md-12">
            {% if users.items %}

                {% for users in users.items %}
                <div class="post-entry-2 d-flex bg-light">
                 <div class="thumbnail" style="background-image: url('{{ url_for('static', filename= 'images/' + users.profile_pic) }}')"></div>

                  <div class="contents">
                    <h2><a href="{{ url_for('user.user_profile', user_id=users.id ) }}">Name: {{users.name}}</a></h2>
                    <div class="post-meta">
                      <span class="d-block">Username : {{users.username}}</span>
                      <span class="d-block">Email : <a href="mailto: {{ users.email }}">{{users.email}}</a></span>
                      <span class="d-block">Designation : {{ users.designation|capitalize }}</span>
                      <span class="d-block">Recipe Posted : {{ users.recipes|length }}</span>
                    </div>
                  </div>
                </div>
                {% endfor %}
                  {% else %}
                  <p>There are no recipe contributors at this moment.</p>
                  {% endif %}
              </div>





          </div>
        </div>

          {% if users %}

          <div class="mx-auto">
                <br>
              <nav aria-label="Page navigation example">
              <ul class="pagination">

                  {% if users.page > 1 %}
                <li class="page-item"><a class="page-link" href="{{ url_for('cooks', page=(users.page-1)) }}">Previous</a></li>
                  {% else %}
                <li class="page-item disabled"><a class="page-link" href="">Previous</a></li>
                  {% endif %}


                  {% for page_num in users.iter_pages(left_edge=1, right_edge=1, left_current=2, right_current=2) %}
                    {% if page_num %}


                <li class="page-item"><a class="page-link" href="{{ url_for('cooks', page=page_num) }}">{{page_num}}</a></li>
                    {% else %}
                  <li class="page-item"><a class="page-link" href="">....</a></li>
                    {% endif %}
                  {% endfor %}

                  {% if users.page < users.pages %}
                <li class="page-item"><a class="page-link" href="{{ url_for('cooks', page=(users.page+1)) }}">Next</a></li>
                  {% else %}
                <li class="page-item disabled"><a class="page-link" href="">Next</a></li>
                  {% endif %}

              </ul>
            </nav>

          </div>
                  {% else %}
                  {% endif %}

      </div>
      </div>
    </div>

{% endblock %}

App/templates/user/index.html
{% extends "user/base.html" %}

{% block content %}


    <div class="site-section py-0">
      <div class="owl-carousel hero-slide owl-style">

        {% if editor_recipe %}
        {% for recipe in editor_recipe %}
        <div class="site-section">
          <div class="container">
            <div class="half-post-entry d-block d-lg-flex bg-light">
              <div class="img-bg" style="background-image: url('{{ url_for('static', filename= 'images/' + recipe.image) }}')"></div>
              <div class="contents">
                <span class="caption">Editor's Pick</span>
                <h2><a href="{{ url_for('single_recipe', recipe_id=recipe.id ) }}">{{recipe.title}}</a></h2>
                <p class="mb-3">{{recipe.description[:250]}}... <a href="{{ url_for('single_recipe', recipe_id=recipe.id ) }}">Read more</a></p>
                <div class="post-meta">
                  <span class="d-block">Author: <a href="#">{{recipe.recipe_creator.name}}</a></span>
                  <span class="date-read">

                    {% if recipe.approval < 0 %}
                        Not Verified <span class="mx-1">&bullet;</span>
                    {% elif recipe.approval > 0 %}
                        Admin Verified <span class="icon-star2"></span>
                    {% else %}
                        Rejected
                    {% endif %}

                  </span>
                </div>

              </div>
            </div>
          </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="site-section">
          <div class="container">
            <div class="half-post-entry d-block d-lg-flex bg-light">
              <div class="img-bg" style="background-image: url('{{ url_for('static', filename='images/register.jpg') }}')"></div>
              <div class="contents">
                <span class="caption">Publish a Recipe Now!</span>
                <h2><a href="">Have a recipe? Publish it on Onion</a></h2>
                  <p class="mb-3">Share your story through your dishes to our community of Food enthusiasts. Onion provides a variety of support from selling your homemade ingredients to finding your dream job by creating a public portfolio for Chefs</p>
                <div class="post-meta">
                  <span class="d-block"><a href="{{ url_for('user.publish_recipe') }}">Publish Now</a></span>
                </div>

              </div>
            </div>
          </div>
        </div>
        {% endif %}




      </div>
    </div>


    <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="row">
              <div class="col-12">
                <div class="section-title">
                  <h2>Top Contributors</h2>
                </div>
              </div>
            </div>
            <div class="row">

              <div class="col-md-6">
                <div class="post-entry-1">
                  <a href="post-single.html"><img src="{{ url_for('static', filename='images/register.jpg') }}" alt="Image" class="img-fluid"></a>
                  <h2><a href="">Have a recipe? Publish it on Onion</a></h2>
                  <p>Share your story through your dishes to our community of Food enthusiasts. Onion provides a variety of support from selling your homemade ingredients to finding your dream job by creating a public portfolio for Chefs</p>
                  <div class="post-meta">
                  <span class="d-block"><a href="{{ url_for('user.publish_recipe') }}">Publish Now</a></span>

                  </div>
                </div>
              </div>


              <div class="col-md-6">
                {% if users.items %}

                {% for users in users.items %}

                <div class="post-entry-2 d-flex bg-light">
                 <div class="thumbnail" style="background-image: url('{{ url_for('static', filename= 'images/' + users.profile_pic) }}')"></div>

                  <div class="contents">
                    <h2><a href="{{ url_for('user.user_profile', user_id=users.id ) }}">{{users.name}}</a></h2>
                    <div class="post-meta">
                      <span class="d-block">Email : <a href="mailto: {{ users.email }}">{{users.email}}</a></span>
                      <span class="d-block">Recipe Posted : {{ users.recipes|length }}</span>
                      <span class="d-block">Designation : {{ users.designation|capitalize }}</span>

                    </div>
                  </div>
                </div>
                {% endfor %}
                  {% else %}
                  <p>There are no recipe contributors at this moment.</p>
                  {% endif %}



              </div>
            </div>
          </div>


          <div class="col-lg-3 ml-auto">
            <div class="section-title">
              <h2>Featured Recipes</h2>
            </div>
              {% if featured %}
            {% for featured in featured %}
            <div class="trend-entry d-flex">
              <div class="trend-contents">
                <h2><a href="blog-single.html">{{featured.title}}</a></h2>
                <div class="post-meta">
                  <span class="d-block"><a href="{{ url_for('user.user_profile', user_id=featured.recipe_creator.id ) }}">{{featured.recipe_creator.name}}</a></span>
                  <span class="date-read">

                      {% if featured.approval < 0 %}
                        Not Verified <span class="mx-1">&bullet;</span>
                    {% elif featured.approval > 0 %}
                        Admin Verified <span class="icon-star2"></span>
                    {% else %}
                        Rejected
                    {% endif %}

                  </span>
                </div>
              </div>
            </div>
              {% else %}
              <p>There are no featured recipe at this moment</p>
            {% endfor %}
              {% endif %}

            <p>
              <a href="{{ url_for('user.recipes') }}" class="more">See All Recipes <span class="icon-keyboard_arrow_right"></span></a>
            </p>
          </div>

        </div>
      </div>
    </div>



{% endblock %}

App/templates/user/my_recipes.html
{% extends "user/base.html" %}

{% block content %}
    <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="row">
              <div class="col-12">
                <div class="section-title">

                  <h2>My Recipes

                    {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for msg in messages %}
                  : {{msg}}
                    {% endfor %}
                {% else %}

                {% endif %}
                {% endwith %}

                  </h2>
                </div>
              </div>
            </div>


            <div class="row">

              <div class="col-md-12">



                <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Title</th>
                <th>Status</th>
                <th>Featured As</th>
                <th>#</th>
            </tr>
        </thead>
        <tbody>
        {% for recipe in recipes %}
            <tr>
                <td><a style="color: #0b0b0b" href="{{ url_for('user.single_recipe', recipe_id=recipe.id ) }}">{{recipe.title}}</a></td>
                <td>

                    {% if recipe.approval < 0 %}
                        Pending
                    {% elif recipe.approval > 0 %}
                        Approved
                    {% else %}
                        Rejected
                    {% endif %}


                </td>
                <td>{% if recipe.status == 1 %}
                    Editor's Pick
                    {% elif recipe.status == 2 %}
                    Weekly Featured
                    {% else %}
                        Normal
                    {% endif %}
                </td>

                <td>

                  <div class="dropdown d-inline-block p-0">
              <button class="btn btn-primary py-0 px-2 dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Controls
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="{{ url_for('user.edit_recipe', recipe_id=recipe.id ) }}">Edit Recipe</a>
                <a class="dropdown-item" href="{{ url_for('user.delete_recipe', recipe_id=recipe.id ) }}">Delete</a>

              </div>
            </div>

                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>


          </div>





        </div>
      </div>
    </div>
{% endblock %}

App/templates/user/recipes.html
{% extends "user/base.html" %}

{% block content %}

    <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="section-title">
              <h2>All Recipes</h2>
            </div>
            {% if recipes.items %}

            {% for recipe in recipes.items %}
            <div class="post-entry-2 d-flex">
              <div class="thumbnail order-md-1" style="background-image: url('{{ url_for('static', filename= 'images/' + recipe.image) }}')"></div>



                <div class="contents order-md-2">
                <div class="float-right"><h2><a href="{{ url_for('user.save_recipe', recipe_id=recipe.id ) }}">
                                       <u>Save Recipe</u> </a> </h2></div>


                <h2><a href="{{ url_for('user.single_recipe', recipe_id=recipe.id ) }}">{{recipe.title}}</a></h2><br>
                <p class="mb-3">{{recipe.description[:250]}} <a href="{{ url_for('user.single_recipe', recipe_id=recipe.id ) }}">Read more...</a></p>
                <div class="post-meta">
                  <span class="d-block">Author: <a href="#">{{recipe.recipe_creator.name}}</a></span>
                  <span class="date-read">

                    {% if recipe.approval < 0 %}
                        Not Verified <span class="mx-1">&bullet;</span>
                    {% elif recipe.approval > 0 %}
                        Admin Verified <span class="icon-star2"></span>
                    {% else %}
                        Rejected
                    {% endif %}

                  </span>
                </div>
              </div>
            </div>
            {% endfor %}
            {% else %}
            <p>There are no recipes published yet.</p>
            {% endif %}
          </div>

          {% if recipes %}

          <div class="mx-auto">
                <br>
              <nav aria-label="Page navigation example">
              <ul class="pagination">

                  {% if recipes.page > 1 %}
                <li class="page-item"><a class="page-link" href="{{ url_for('recipes', page=(recipes.page-1)) }}">Previous</a></li>
                  {% else %}
                <li class="page-item disabled"><a class="page-link" href="">Previous</a></li>
                  {% endif %}


                  {% for page_num in recipes.iter_pages(left_edge=1, right_edge=1, left_current=2, right_current=2) %}
                    {% if page_num %}


                <li class="page-item"><a class="page-link" href="{{ url_for('recipes', page=page_num) }}">{{page_num}}</a></li>
                    {% else %}
                  <li class="page-item"><a class="page-link" href="">....</a></li>
                    {% endif %}
                  {% endfor %}

                  {% if recipes.page < recipes.pages %}
                <li class="page-item"><a class="page-link" href="{{ url_for('recipes', page=(users.page+1)) }}">Next</a></li>
                  {% else %}
                <li class="page-item disabled"><a class="page-link" href="">Next</a></li>
                  {% endif %}

              </ul>
            </nav>

          </div>
                  {% else %}
                  {% endif %}

        </div>
      </div>
    </div>


{% endblock %}

App/templates/user/saved.html
{% extends "user/base.html" %}

{% block content %}
    <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="row">
              <div class="col-12">
                <div class="section-title">

                  <h2>Saved Recipes

                    {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for msg in messages %}
                  : {{msg}}
                    {% endfor %}
                {% else %}

                {% endif %}
                {% endwith %}

                  </h2>
                </div>
              </div>
            </div>


            <div class="row">

              <div class="col-md-12">



                <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Title</th>
                <th>Author</th>
                <th>Featured As</th>
                <th>#</th>
            </tr>
        </thead>
        <tbody>
        {% for saved in saves %}
            <tr>
                <td><a style="color: #0b0b0b" href="{{ url_for('user.single_recipe', recipe_id=saved.saved_recipe.id ) }}">{{saved.saved_recipe.title}}</a></td>
                <td>{{saved.saved_recipe.recipe_creator.name}}</td>
                <td>{% if saved.saved_recipe.status == 1 %}
                    Editor's Pick
                    {% elif saved.saved_recipe.status == 2 %}
                    Weekly Featured
                    {% else %}
                        Normal
                    {% endif %}
                </td>

                <td>

                  <div class="dropdown d-inline-block p-0">
              <button class="btn btn-primary py-0 px-2" type="button" aria-expanded="false">
                  <a href="{{ url_for('user.remove_saved', save_id=saved.id ) }}">Remove</a>
              </button>
            </div>

                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>


          </div>





        </div>
      </div>
    </div>
{% endblock %}

App/templates/user/single.html
{% extends "user/base.html" %}

{% block content %}

    <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 single-content">

            <p class="mb-5">
              <img src="{{ url_for('static', filename= 'images/' + recipe.image) }}" alt="Image" class="img-fluid">
            </p>
            <h1 class="mb-4">
              {{recipe.title}}
            </h1>
            <div class="post-meta d-flex mb-5">
              <div class="bio-pic mr-3">
                <img src="{{ url_for('static', filename= 'images/' + recipe.recipe_creator.profile_pic) }}" alt="Image" class="img-fluidid">
              </div>
              <div class="vcard">
                <span class="d-block">Author: <a href="{{ url_for('user.user_profile', user_id=recipe.recipe_creator.id ) }}">{{recipe.recipe_creator.name}}</a></span>
                <span class="read">
                    {% if recipe.approval < 0 %}
                        Not Verified <span class="mx-1">&bullet;</span>
                    {% elif recipe.approval > 0 %}
                        Admin Verified <span class="icon-star2"></span>
                    {% else %}
                        Rejected
                    {% endif %}</span>
              </div>
            </div>

            <p>{{recipe.description}}</p>


            <div class="pt-5">

                <h4 style="color: black">Ingredients</h4><br>
                {% for ingredient in ingredients %}
                    <li>{{ingredient}}</li>
                {% endfor %}

            </div>



          </div>


          <div class="col-lg-3 ml-auto">
            <div class="section-title">
              <h2>Featured Recipes</h2>
            </div>
              {% if featured %}
            {% for featured in featured %}
            <div class="trend-entry d-flex">
              <div class="trend-contents">
                <h2><a href="blog-single.html">{{featured.title}}</a></h2>
                <div class="post-meta">
                  <span class="d-block"><a href="{{ url_for('user.user_profile', user_id=featured.recipe_creator.id ) }}">{{featured.recipe_creator.name}}</a></span>
                  <span class="date-read">

                      {% if featured.approval < 0 %}
                        Not Verified <span class="mx-1">&bullet;</span>
                    {% elif featured.approval > 0 %}
                        Admin Verified <span class="icon-star2"></span>
                    {% else %}
                        Rejected
                    {% endif %}

                  </span>
                </div>
              </div>
            </div>
              {% else %}
              <p>There are no featured recipe at this moment</p>
            {% endfor %}
              {% endif %}

            <p>
              <a href="{{ url_for('user.recipes') }}" class="more">See All Recipes <span class="icon-keyboard_arrow_right"></span></a>
            </p>
          </div>


        </div>

      </div>
    </div>


{% endblock %}